version: "3.7"
services:
  node:
    build:
      context: ./
      target: v0.1
    image: "geiser/gamification-workbench"
    container_name: "gamification-workbench_app"
    restart: unless-stopped
    tty: true
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports:
      - "8080:3000"
    command: "npm start"