version: "3.7"
services:
  node:
    build:
      context: ./
      target: dev
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: npm run start
    ports:
      - "8066:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*