version: "3.7"
services:
  node:
    image: "geiser/gamification-workbench:latest"
    container_name: "gamification-workbench_breno"
    restart: unless-stopped
    tty: true
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports:
      - "8075:3000"
    command: "npm start"
